# Generated by Django 3.2.4 on 2021-07-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizennid', '0003_auto_20210727_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=60)),
                ('village_id', models.CharField(blank=True, help_text='Village code', max_length=17, null=True, unique=True)),
                ('village_code_old', models.CharField(blank=True, max_length=15, null=True)),
                ('word_no', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='citizennid',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citizennid.village'),
        ),
    ]
