# Generated by Django 3.2.4 on 2021-07-27 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizennid', '0004_auto_20210727_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizennid',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='citizennid.village'),
        ),
    ]
